Writable:
  LogLevel: DEBUG
Service:
  Host: 192.168.8.216
  Port: 59995
  StartupMsg: device uart started

Device:
  # These have common values (currently), but must be here for service local env overrides to apply when customized
  ProfilesDir: "./res/profiles"
  DevicesDir: "./res/devices"